using System;using System.Collections.Generic;using SarmatVisionHold.KestrelClient.Control;
internal static class Program {
 static int passed;static readonly Guid Id=Guid.Parse("123e4567-e89b-12d3-a456-426614174000");
 static int Main(){var tests=new Action[]{Signs,ConstantErrorBuildsIntegral,ZeroErrorKeepsTrim,ResetAndFreezeRules,AntiWindupAndReversal,DtAndUnits,AcknowledgementGate,SaturationState,PositionHoldReturnsToAnchor};try{foreach(var test in tests){test();passed++;Console.WriteLine("PASS "+test.Method.Name);}Console.WriteLine($"All {passed} control test groups passed.");return 0;}catch(Exception e){Console.Error.WriteLine(e);return 1;}}
 static VisionControlOptions Options()=>new VisionControlOptions{Mode=VisionControlMode.CONTROL,VelocityUnits=VisionVelocityUnits.Pxps,DeadbandVelocity=2,RecoveryGoodFrames=1,FlowLowPassAlpha=1,DerivativeLowPassAlpha=1,MaxSlewRatePerSecond=100,KpX=.0025,KpY=.0025,KiX=.01,KiY=.01,KdX=0,KdY=0,MaxCommand=.2,MaxIntegralContribution=.15,IntegralClampX=100,IntegralClampY=100,RequireAcknowledgement=false,EnablePositionHold=false};
 static VisionControlInput Input(uint frame=1,double flowX=-10,double flowY=0,double dt=.05)=>new VisionControlInput{SessionId=Id,FrameNumber=frame,TimestampUs=(ulong)(frame*dt*1000000),DeltaSeconds=dt,TextureFlowX=flowX,TextureFlowY=flowY,Quality=1,AltitudeMeters=10,HorizontalFovDegrees=90,ImageWidth=100,ImageHeight=100};
 static void Signs(){var c=new VisionVelocityDampingController(Options());var right=c.Update(Input(flowX:-10));True(right.RollCommand<0,"right motion must command left acceleration");c.Reset();var left=c.Update(Input(flowX:10));True(left.RollCommand>0,"left motion must command right acceleration");c.Reset();var forward=c.Update(Input(flowY:10));True(forward.PitchCommand<0,"forward motion must command backward acceleration");c.Reset();var backward=c.Update(Input(flowY:-10));True(backward.PitchCommand>0,"backward motion must command forward acceleration");}
 static void ConstantErrorBuildsIntegral(){var c=new VisionVelocityDampingController(Options());double first=0,last=0;for(uint n=1;n<=20;n++){var x=c.Update(Input(n));if(n==1)first=x.ITermX;last=x.ITermX;}True(Math.Abs(last)>Math.Abs(first));True(Math.Abs(last)>0);}
 static void ZeroErrorKeepsTrim(){var c=new VisionVelocityDampingController(Options());for(uint n=1;n<=10;n++)c.Update(Input(n));var before=c.IntegralX;var zero=c.Update(Input(11,0));Eq(before,c.IntegralX,1e-9);True(Math.Abs(zero.ITermX)>0);}
 static void ResetAndFreezeRules(){var c=new VisionVelocityDampingController(Options());for(uint n=1;n<=5;n++)c.Update(Input(n));var trim=c.IntegralX;var degraded=Input(6);degraded.Quality=0;Eq(VisionControlState.DEGRADED,c.Update(degraded).State);Eq(trim,c.IntegralX,1e-9);var lost=Input(7);lost.Lost=true;Eq(VisionControlState.LOST,c.Update(lost).State);Eq(0,c.IntegralX,1e-9);c.Update(Input(8));var pilot=Input(9);pilot.PilotRoll=.2;Eq(VisionControlState.PILOT_OVERRIDE,c.Update(pilot).State);Eq(0,c.IntegralX,1e-9);c.Update(Input(10));var disconnected=Input(11);disconnected.Connected=false;Eq(VisionControlState.DISCONNECTED,c.Update(disconnected).State);Eq(0,c.IntegralX,1e-9);c.Update(Input(12));var changed=Input(1);changed.SessionId=Guid.NewGuid();c.Update(changed);Eq(0,c.IntegralX,1e-9);}
 static void AntiWindupAndReversal(){var o=Options();o.KiX=1;o.KpX=1;o.IntegralClampX=100;var c=new VisionVelocityDampingController(o);VisionControlOutput saturated=null;for(uint n=1;n<=40;n++)saturated=c.Update(Input(n,-100));True(Math.Abs(c.IntegralX)<=o.IntegralClampX,"anti-windup bounded integral");True(Math.Abs(saturated.ITermX)<=o.MaxIntegralContribution);var before=c.IntegralX;var reversed=c.Update(Input(41,100));True(reversed.RollCommand>0);True(c.IntegralX<before);}
 static void DtAndUnits(){var a=new VisionVelocityDampingController(Options());for(uint n=1;n<=10;n++)a.Update(Input(n,-10,dt:.05));var b=new VisionVelocityDampingController(Options());for(uint n=1;n<=5;n++)b.Update(Input(n,-10,dt:.1));Eq(a.IntegralX,b.IntegralX,.05);double x=100,y=100;var i=Input();VisionCoordinateMapper.ConvertVelocityUnits(i,VisionVelocityUnits.Mps,ref x,ref y);Eq(20,x,1e-9);Eq(20,y,1e-9);var invalid=Input(11);invalid.DeltaSeconds=1;Eq(VisionControlState.FAILSAFE,a.Update(invalid).State);}
 static void AcknowledgementGate(){var o=Options();o.RequireAcknowledgement=true;o.AcknowledgementTimeoutMs=10000;var c=new VisionVelocityDampingController(o);var i=Input();var first=c.Update(i);var message=c.Message(i,first);var pending=c.Update(Input(2));True(pending.State!=VisionControlState.FAILSAFE,"one-frame acknowledgement lag must not trip failsafe");var second=c.Message(Input(2),pending);c.UpdateAcknowledgement(new VisionControlStatus{Type="visionControlStatus",ProtocolVersion=1,SessionId=Id,LastReceivedSequence=message.CommandSequence,LastAppliedSequence=message.CommandSequence,Accepted=true,ControllerEnabled=true,ReceivedUtc=DateTime.UtcNow});var applied=c.Update(Input(3));True(applied.Acknowledged,"an applied sequence may safely lag the latest sent sequence");True(second.CommandSequence>message.CommandSequence);True(Math.Abs(c.IntegralX)>0);}
 static void SaturationState(){var o=Options();o.KpX=1;var c=new VisionVelocityDampingController(o);var x=c.Update(Input(flowX:-100));Eq(VisionControlState.SATURATED,x.State);True(x.Saturated);True(c.SaturationPercentage>0);}
 static void PositionHoldReturnsToAnchor(){var o=Options();o.EnablePositionHold=true;o.KpX=o.KpY=o.KiX=o.KiY=0;o.PositionKpX=o.PositionKpY=.1;o.MaxCommand=.65;var c=new VisionVelocityDampingController(o);var moved=c.Update(Input(1,-10,0,.1));True(moved.PositionX>0,"rightward optical motion must accumulate rightward displacement");True(moved.PositionTermX<0,"position loop must command back toward the anchor");var stopped=c.Update(Input(2,0,0,.1));True(stopped.RollCommand<0,"correction must remain after velocity reaches zero until the anchor is recovered");}
 static void True(bool x,string message="expected true"){if(!x)throw new Exception(message);}static void Eq<T>(T expected,T actual){if(!EqualityComparer<T>.Default.Equals(expected,actual))throw new Exception($"expected {expected}, got {actual}");}static void Eq(double expected,double actual,double tolerance){if(Math.Abs(expected-actual)>tolerance)throw new Exception($"expected {expected}, got {actual}");}
}
