using System;using System.Buffers.Binary;using System.Collections.Generic;using System.Threading;using OpenCvSharp;using SarmatVisionHold.KestrelClient.Control;using SarmatVisionHold.KestrelClient.Models;using SarmatVisionHold.KestrelClient.Networking;using SarmatVisionHold.KestrelClient.Processing;using SarmatVisionHold.Vision;
internal static class Program { static int passed;static int Main(){var tests=new Action[]{ValidKdvf,InvalidKdvf,TelemetryParsing,TelemetryRejects,FrameFirst,TelemetryFirst,DuplicatesAndOrder,Timeouts,GroundTruthDirections,GroundTruthClasses,ValidatorStates};try{foreach(var t in tests){t();passed++;Console.WriteLine("PASS "+t.Method.Name);}Console.WriteLine($"All {passed} Kestrel client test groups passed.");return 0;}catch(Exception e){Console.Error.WriteLine(e);return 1;}}
 static void ValidKdvf(){var d=new KdvfFrameDecoder();var bytes=FrameBytes();True(d.TryDecode(bytes,out var f,out var e),e);using(f){Eq(Id,f.SessionId);Eq((uint)7,f.FrameNumber);Eq((ulong)123456,f.TimestampUs);Eq(4,f.Image.Width);}}
 static void InvalidKdvf(){var d=new KdvfFrameDecoder();var b=FrameBytes();b[0]=0;False(d.TryDecode(b,out _,out _));b=FrameBytes();BinaryPrimitives.WriteUInt16LittleEndian(new Span<byte>(b,6,2),45);False(d.TryDecode(b,out _,out _));b=FrameBytes();BinaryPrimitives.WriteUInt32LittleEndian(new Span<byte>(b,42,4),99);False(d.TryDecode(b,out _,out _));b=FrameBytes();b[40]=2;False(d.TryDecode(b,out _,out _));False(new KdvfFrameDecoder(1).TryDecode(FrameBytes(),out _,out _));}
 static void TelemetryParsing(){True(new TelemetryMessageParser().TryParse(Json(),out var t,out var e),e);Eq(Id,t.SessionId);Eq(3d,t.VelocityBody.Z);Eq(-1.5708,t.Camera.MountPitchRad);}
 static void TelemetryRejects(){var p=new TelemetryMessageParser();False(p.TryParse(Json().Replace("\"protocolVersion\":1","\"protocolVersion\":2"),out _,out _));False(p.TryParse(Json().Replace("\"x\":1,\"y\":2,\"z\":3","\"x\":\"NaN\",\"y\":2,\"z\":3"),out _,out _));}
 static void FrameFirst(){var s=new FrameTelemetrySynchronizer();var f=Frame();True(s.Add(f)==null);using(var x=s.Add(Telemetry())){True(x!=null);Eq(1L,s.Counters.Matched);}}
 static void TelemetryFirst(){var s=new FrameTelemetrySynchronizer();True(s.Add(Telemetry())==null);using(var x=s.Add(Frame()))True(x!=null);}
 static void DuplicatesAndOrder(){var s=new FrameTelemetrySynchronizer();s.Add(Frame());s.Add(Frame());Eq(1L,s.Counters.DuplicateFrame);var s2=new FrameTelemetrySynchronizer();var t=Telemetry();s2.Add(t);s2.Add(t);Eq(1L,s2.Counters.DuplicateTelemetry);var t2=Telemetry();t2.FrameNumber=8;s2.Add(t2);var t3=Telemetry();t3.FrameNumber=2;s2.Add(t3);True(s2.Counters.OutOfOrder>0);s.Reset();s2.Reset();}
 static void Timeouts(){var s=new FrameTelemetrySynchronizer(5,4);s.Add(Frame());Thread.Sleep(10);var t=Telemetry();t.FrameNumber=8;s.Add(t);Eq(1L,s.Counters.FrameWithoutTelemetry);s.Reset();True(s.Counters.TelemetryWithoutFrame>0);}
 static void GroundTruthDirections(){var e=new GroundTruthMotionEstimator(.01,.01);var t=Telemetry();t.Camera.MountPitchRad=0;t.VelocityBody=new Vector3Data{X=1};var g=e.Estimate(t);Eq("LEFT",g.TextureDirection);t.VelocityBody.X=-1;Eq("RIGHT",e.Estimate(t).TextureDirection);t.VelocityBody=new Vector3Data();t.AngularRateBody.Z=1;Eq("CW",e.Estimate(t).RotationDirection);t.AngularRateBody.Z=-1;Eq("CCW",e.Estimate(t).RotationDirection);}
 static void GroundTruthClasses(){var e=new GroundTruthMotionEstimator(.01,.01);var t=Telemetry();t.Camera.MountPitchRad=0;t.VelocityBody=new Vector3Data();t.AngularRateBody.Z=0;Eq(ExpectedMotion.Still,e.Estimate(t).Classification);t.VelocityBody.X=1;Eq(ExpectedMotion.Translating,e.Estimate(t).Classification);t.VelocityBody.X=0;t.AngularRateBody.Z=1;Eq(ExpectedMotion.Rotating,e.Estimate(t).Classification);t.VelocityBody.X=1;Eq(ExpectedMotion.Mixed,e.Estimate(t).Classification);}
 static void ValidatorStates(){var v=new MotionValidator();var f=new SparseOpticalFlowResult{Status=FlowTrackingStatus.OK,Quality=1,RotationDegrees=-1};var d=new MotionDecision{SmoothedClass="STILL",TextureMotion="STILL"};Eq(ValidationStatus.PASS,v.Validate(f,d,new GroundTruthMotion{Classification=ExpectedMotion.Still,TextureDirection="STILL"}).Status);d.SmoothedClass="TRANSLATING_LEFT";d.TextureMotion="RIGHT";Eq(ValidationStatus.PARTIAL,v.Validate(f,d,new GroundTruthMotion{Classification=ExpectedMotion.Translating,TextureDirection="LEFT"}).Status);d.SmoothedClass="ROTATING_CW";Eq(ValidationStatus.FAIL,v.Validate(f,d,new GroundTruthMotion{Classification=ExpectedMotion.Translating}).Status);f.Quality=0;Eq(ValidationStatus.UNKNOWN,v.Validate(f,d,new GroundTruthMotion{Classification=ExpectedMotion.Rotating}).Status);}
 static readonly Guid Id=Guid.Parse("00112233-4455-6677-8899-aabbccddeeff");static byte[] FrameBytes(){byte[] jpg;using(var m=new Mat(3,4,MatType.CV_8UC3,new Scalar(10,20,30)))Cv2.ImEncode(".jpg",m,out jpg);var b=new byte[46+jpg.Length];b[0]=75;b[1]=68;b[2]=86;b[3]=70;BinaryPrimitives.WriteUInt16LittleEndian(new Span<byte>(b,4,2),1);BinaryPrimitives.WriteUInt16LittleEndian(new Span<byte>(b,6,2),46);var raw=Hex("00112233445566778899aabbccddeeff");Buffer.BlockCopy(raw,0,b,8,16);BinaryPrimitives.WriteUInt64LittleEndian(new Span<byte>(b,24,8),123456);BinaryPrimitives.WriteUInt32LittleEndian(new Span<byte>(b,32,4),7);BinaryPrimitives.WriteUInt16LittleEndian(new Span<byte>(b,36,2),4);BinaryPrimitives.WriteUInt16LittleEndian(new Span<byte>(b,38,2),3);b[40]=1;BinaryPrimitives.WriteUInt32LittleEndian(new Span<byte>(b,42,4),(uint)jpg.Length);Buffer.BlockCopy(jpg,0,b,46,jpg.Length);return b;}static KestrelFrame Frame(){new KdvfFrameDecoder().TryDecode(FrameBytes(),out var f,out _);return f;}static KestrelTelemetry Telemetry()=>new KestrelTelemetry{SessionId=Id,FrameNumber=7,TimestampUs=123456,VelocityBody=new Vector3Data{X=1,Y=2,Z=3},VelocityWorld=new Vector3Data(),Position=new Vector3Data(),AngularRateBody=new Vector3Data(),WindWorld=new Vector3Data(),Attitude=new AttitudeData(),Camera=new CameraData{MountPitchRad=-1.5708},State=new StateData(),ReceivedUtc=DateTime.UtcNow};
 static string Json()=>"{\"type\":\"telemetry\",\"protocolVersion\":1,\"sessionId\":\"00112233-4455-6677-8899-aabbccddeeff\",\"frameNumber\":7,\"timestampUs\":123456,\"simulationTimeSeconds\":.123456,\"position\":{\"x\":1,\"y\":2,\"z\":3},\"velocityWorld\":{\"x\":1,\"y\":2,\"z\":3},\"velocityBody\":{\"x\":1,\"y\":2,\"z\":3},\"attitude\":{\"rollRad\":0,\"pitchRad\":0,\"yawRad\":0},\"angularRateBody\":{\"x\":0,\"y\":0,\"z\":0},\"windWorld\":{\"x\":0,\"y\":0,\"z\":0},\"camera\":{\"width\":4,\"height\":3,\"fovDegrees\":90,\"mountRollRad\":0,\"mountPitchRad\":-1.5708,\"mountYawRad\":0},\"state\":{\"paused\":false,\"crashed\":false,\"onGround\":false}}";static byte[] Hex(string s){var b=new byte[s.Length/2];for(int i=0;i<b.Length;i++)b[i]=Convert.ToByte(s.Substring(i*2,2),16);return b;}static void True(bool x,string m=null){if(!x)throw new Exception(m??"expected true");}static void False(bool x)=>True(!x);static void Eq<T>(T a,T b){if(!EqualityComparer<T>.Default.Equals(a,b))throw new Exception($"expected {a}, got {b}");}
}
