using System;
using System.Collections.Generic;
using System.Linq;
using OpenCvSharp;

namespace SarmatVisionHold.Vision
{
 public enum FlowTrackingStatus { OK, DEGRADED, LOST }
 public sealed class SparseOpticalFlowOptions
 {
  public int MaxFeatures=300; public double QualityLevel=.01; public double MinimumDistance=8;
  public int LkWindowSize=21; public int PyramidLevels=3; public double ForwardBackwardErrorThreshold=1.5;
  public double OutlierThreshold=3; public int MinimumAcceptedPoints=20;public double RansacReprojectionThreshold=2;public double RansacConfidence=.99;public int RansacMaxIterations=2000;
  public void Normalize(){MaxFeatures=Clamp(MaxFeatures,1,10000);QualityLevel=Finite(QualityLevel)?Clamp(QualityLevel,.000001,1):.01;MinimumDistance=Finite(MinimumDistance)?Clamp(MinimumDistance,0,10000):8;LkWindowSize=Clamp(LkWindowSize,3,255);if(LkWindowSize%2==0)LkWindowSize++;PyramidLevels=Clamp(PyramidLevels,0,8);ForwardBackwardErrorThreshold=Finite(ForwardBackwardErrorThreshold)?Clamp(ForwardBackwardErrorThreshold,0,1000):1.5;OutlierThreshold=Finite(OutlierThreshold)?Clamp(OutlierThreshold,0,10000):3;MinimumAcceptedPoints=Clamp(MinimumAcceptedPoints,1,MaxFeatures);RansacReprojectionThreshold=Finite(RansacReprojectionThreshold)?Clamp(RansacReprojectionThreshold,.01,1000):2;RansacConfidence=Finite(RansacConfidence)?Clamp(RansacConfidence,.01,.999999):.99;RansacMaxIterations=Clamp(RansacMaxIterations,10,100000);}
  static int Clamp(int v,int a,int b)=>Math.Max(a,Math.Min(b,v));static double Clamp(double v,double a,double b)=>Math.Max(a,Math.Min(b,v));static bool Finite(double v)=>!double.IsNaN(v)&&!double.IsInfinity(v);
 }
 public sealed class FlowTrack
 { public Point2f From;public Point2f To;public bool ForwardTracked;public bool Accepted;public bool RansacInlier;public double ForwardBackwardError;public string RejectionReason;public double Dx=>To.X-From.X;public double Dy=>To.Y-From.Y; }
 public sealed class SparseOpticalFlowResult
 { public int DetectedPoints;public int TrackedPoints;public int AcceptedPoints;public int InlierCount;public double InlierRatio;public double MedianX;public double MedianY;public double TranslationX;public double TranslationY;public double RotationDegrees;public double Scale=1;public double Magnitude;public double Quality;public FlowTrackingStatus Status;public string Reason;public IReadOnlyList<FlowTrack> Tracks=new FlowTrack[0]; }
 public sealed class SparseOpticalFlowProcessor:IDisposable
 {
  readonly SparseOpticalFlowOptions options;Mat previous;
  public SparseOpticalFlowProcessor(SparseOpticalFlowOptions options=null){this.options=options??new SparseOpticalFlowOptions();this.options.Normalize();}
  public SparseOpticalFlowResult Process(Mat gray,Mat mask=null){if(gray==null||gray.Empty()){return Lost("Empty frame");}using(var current=EnsureGray(gray)){if(previous==null){previous=current.Clone();return Lost("Initializing");}var result=Calculate(previous,current,mask);previous.Dispose();previous=current.Clone();return result;}}
  SparseOpticalFlowResult Calculate(Mat before,Mat after,Mat mask){Point2f[] points;try{points=before.GoodFeaturesToTrack(options.MaxFeatures,options.QualityLevel,options.MinimumDistance,mask,3,false,.04);}catch(Exception ex){return Lost("Feature detection failed: "+ex.GetType().Name);}if(points==null||points.Length==0)return Lost("No features");
   using(var p0=Mat.FromArray(points))using(var p1=new Mat())using(var forwardStatus=new Mat())using(var forwardError=new Mat()){try{Lk(before,after,p0,p1,forwardStatus,forwardError);}catch(Exception ex){return Lost("Forward LK failed: "+ex.GetType().Name);}using(var back=new Mat())using(var backwardStatus=new Mat())using(var backwardError=new Mat()){try{Lk(after,before,p1,back,backwardStatus,backwardError);}catch(Exception ex){return Lost("Backward LK failed: "+ex.GetType().Name);}var tracks=new List<FlowTrack>(points.Length);for(var i=0;i<points.Length;i++){var forward=ReadStatus(forwardStatus,i);var backward=ReadStatus(backwardStatus,i);var to=forward?ReadPoint(p1,i):points[i];var fb=forward&&backward?Distance(points[i],ReadPoint(back,i)):double.PositiveInfinity;tracks.Add(new FlowTrack{From=points[i],To=to,ForwardTracked=forward,ForwardBackwardError=fb,Accepted=forward&&backward&&Finite(fb)&&fb<=options.ForwardBackwardErrorThreshold,RejectionReason=!forward?"LK":!backward?"FB-LK":fb>options.ForwardBackwardErrorThreshold?"FB-error":null});}
     var candidates=tracks.Where(x=>x.Accepted&&Finite(x.Dx)&&Finite(x.Dy)).ToList();var medianX=Median(candidates.Select(x=>(double)x.Dx));var medianY=Median(candidates.Select(x=>(double)x.Dy));double tx=medianX,ty=medianY,rotation=0,scale=1;if(candidates.Count>=3){var threshold=Math.Min(options.RansacReprojectionThreshold,options.OutlierThreshold);using(var from=Mat.FromArray(candidates.Select(x=>x.From).ToArray()))using(var to=Mat.FromArray(candidates.Select(x=>x.To).ToArray()))using(var inlierMask=new Mat())using(var affine=Cv2.EstimateAffinePartial2D(from,to,inlierMask,RobustEstimationAlgorithms.RANSAC,threshold,(ulong)options.RansacMaxIterations,options.RansacConfidence,10)){if(affine!=null&&!affine.Empty()&&affine.Rows==2&&affine.Cols==3){var a=affine.At<double>(0,0);var b=affine.At<double>(0,1);var c=affine.At<double>(1,0);var d=affine.At<double>(1,1);var ox=affine.At<double>(0,2);var oy=affine.At<double>(1,2);var cx=before.Width/2d;var cy=before.Height/2d;tx=a*cx+b*cy+ox-cx;ty=c*cx+d*cy+oy-cy;scale=Math.Sqrt(a*a+c*c);rotation=Math.Atan2(c,a)*180/Math.PI;for(var i=0;i<candidates.Count;i++){var inside=ReadStatus(inlierMask,i);candidates[i].RansacInlier=inside;if(!inside){candidates[i].Accepted=false;candidates[i].RejectionReason="RANSAC";}}}}}
     var accepted=tracks.Where(x=>x.Accepted).ToList();medianX=Median(accepted.Select(x=>(double)x.Dx));medianY=Median(accepted.Select(x=>(double)x.Dy));var tracked=tracks.Count(x=>x.ForwardTracked);var ratio=candidates.Count==0?0:(double)accepted.Count/candidates.Count;var quality=Quality(points.Length,tracked,accepted.Count,accepted.Select(x=>x.ForwardBackwardError))*Math.Sqrt(Math.Max(0,ratio));var status=accepted.Count==0?FlowTrackingStatus.LOST:accepted.Count<options.MinimumAcceptedPoints||quality<.35?FlowTrackingStatus.DEGRADED:FlowTrackingStatus.OK;return new SparseOpticalFlowResult{DetectedPoints=points.Length,TrackedPoints=tracked,AcceptedPoints=accepted.Count,InlierCount=accepted.Count,InlierRatio=FiniteOrZero(ratio),MedianX=FiniteOrZero(medianX),MedianY=FiniteOrZero(medianY),TranslationX=FiniteOrZero(tx),TranslationY=FiniteOrZero(ty),RotationDegrees=FiniteOrZero(rotation),Scale=Finite(scale)&&scale>0?scale:1,Magnitude=FiniteOrZero(Math.Sqrt(Square(tx)+Square(ty))),Quality=quality,Status=status,Reason=status==FlowTrackingStatus.OK?"OK":accepted.Count==0?"No affine inliers":"Insufficient affine inliers or quality",Tracks=tracks};}}}
  void Lk(Mat a,Mat b,Mat p0,Mat p1,Mat status,Mat error)=>Cv2.CalcOpticalFlowPyrLK(a,b,p0,p1,status,error,new Size(options.LkWindowSize,options.LkWindowSize),options.PyramidLevels,new TermCriteria(CriteriaTypes.Eps|CriteriaTypes.Count,30,.01),OpticalFlowFlags.None,1e-4);
  static Mat EnsureGray(Mat source){if(source.Channels()==1)return source.Clone();var gray=new Mat();Cv2.CvtColor(source,gray,ColorConversionCodes.BGR2GRAY);return gray;}
  static SparseOpticalFlowResult Lost(string reason)=>new SparseOpticalFlowResult{Status=FlowTrackingStatus.LOST,Reason=reason,Quality=0};
  static bool ReadStatus(Mat m,int i){try{return m.At<byte>(i)!=0;}catch{return false;}}static Point2f ReadPoint(Mat m,int i){try{return m.At<Point2f>(i);}catch{return new Point2f();}}
  static double Quality(int detected,int tracked,int accepted,IEnumerable<double> fb){if(detected<=0||tracked<=0||accepted<=0)return 0;var retention=(double)accepted/detected;var medianFb=Median(fb);var score=retention*Math.Exp(-Math.Max(0,medianFb)/2);return Finite(score)?Math.Max(0,Math.Min(1,score)):0;}
  static double Median(IEnumerable<double> source){var a=source.Where(Finite).OrderBy(x=>x).ToArray();if(a.Length==0)return 0;var mid=a.Length/2;return a.Length%2==0?(a[mid-1]+a[mid])/2:a[mid];}static double Distance(Point2f a,Point2f b)=>Math.Sqrt(Square(a.X-b.X)+Square(a.Y-b.Y));static double Square(double v)=>v*v;static bool Finite(double v)=>!double.IsNaN(v)&&!double.IsInfinity(v);static double FiniteOrZero(double v)=>Finite(v)?v:0;
  public void Reset(){previous?.Dispose();previous=null;}public void Dispose()=>Reset();
 }
}
