using System;
namespace SarmatVisionHold.Vision
{
 public sealed class MotionClassifierOptions
 { public double TranslationThreshold=1;public double RotationThresholdDegrees=.25;public double ScaleThreshold=.003;public double DominanceRatio=1.5;public double SmoothingAlpha=.25;public int HysteresisFrames=3;public void Normalize(){TranslationThreshold=Positive(TranslationThreshold,1);RotationThresholdDegrees=Positive(RotationThresholdDegrees,.25);ScaleThreshold=Positive(ScaleThreshold,.003);DominanceRatio=Math.Max(1,Finite(DominanceRatio)?DominanceRatio:1.5);SmoothingAlpha=Math.Max(.01,Math.Min(1,Finite(SmoothingAlpha)?SmoothingAlpha:.25));HysteresisFrames=Math.Max(1,Math.Min(100,HysteresisFrames));}static double Positive(double v,double d)=>Finite(v)&&v>0?v:d;static bool Finite(double v)=>!double.IsNaN(v)&&!double.IsInfinity(v); }
 public sealed class MotionDecision
 { public string RawClass;public string SmoothedClass;public string TextureMotion;public string EstimatedCameraMotion;public double SmoothedX,SmoothedY,SmoothedRotation,SmoothedScale=1; }
 public sealed class TemporalMotionClassifier
 { readonly MotionClassifierOptions options;bool initialized;double x,y,r,scale=1;string current="STILL",candidate;int candidateCount;
  public TemporalMotionClassifier(MotionClassifierOptions options=null){this.options=options??new MotionClassifierOptions();this.options.Normalize();}
  public MotionDecision Update(SparseOpticalFlowResult f){if(f==null)f=new SparseOpticalFlowResult{Status=FlowTrackingStatus.LOST};var raw=Classify(f.TranslationX,f.TranslationY,f.RotationDegrees,f.Scale,f.Status);if(!initialized){x=f.TranslationX;y=f.TranslationY;r=f.RotationDegrees;scale=f.Scale;current=raw;initialized=true;}else{var a=options.SmoothingAlpha;x=Lerp(x,f.TranslationX,a);y=Lerp(y,f.TranslationY,a);r=Lerp(r,f.RotationDegrees,a);scale=Lerp(scale,f.Scale,a);var proposed=Classify(x,y,r,scale,f.Status);if(proposed==current){candidate=null;candidateCount=0;}else if(proposed==candidate){candidateCount++;if(candidateCount>=options.HysteresisFrames){current=proposed;candidate=null;candidateCount=0;}}else{candidate=proposed;candidateCount=1;}}
   var texture=Direction(x,y);return new MotionDecision{RawClass=raw,SmoothedClass=current,TextureMotion=texture,EstimatedCameraMotion=Opposite(texture),SmoothedX=Safe(x),SmoothedY=Safe(y),SmoothedRotation=Safe(r),SmoothedScale=SafeScale(scale)};}
  string Classify(double tx,double ty,double rotation,double s,FlowTrackingStatus status){if(status==FlowTrackingStatus.LOST)return "LOST";if(status==FlowTrackingStatus.DEGRADED)return "DEGRADED";var tn=Math.Sqrt(tx*tx+ty*ty)/options.TranslationThreshold;var rn=Math.Abs(rotation)/options.RotationThresholdDegrees;var sn=Math.Abs(s-1)/options.ScaleThreshold;if(tn<1&&rn<1&&sn<1)return "STILL";var max=Math.Max(tn,Math.Max(rn,sn));var second=tn+rn+sn-max;if(max<second*options.DominanceRatio)return "MIXED";if(rn==max)return rotation>0?"ROTATING_CCW":"ROTATING_CW";if(sn==max)return s>1?"EXPANDING":"CONTRACTING";return "TRANSLATING_"+Direction(tx,ty);}
  string Direction(double tx,double ty){var ax=Math.Abs(tx);var ay=Math.Abs(ty);if(Math.Sqrt(tx*tx+ty*ty)<options.TranslationThreshold)return "STILL";var horizontal=tx>0?"RIGHT":"LEFT";var vertical=ty>0?"DOWN":"UP";if(ax>ay*1.8)return horizontal;if(ay>ax*1.8)return vertical;return horizontal+"+"+vertical;}
  static string Opposite(string d)=>d.Replace("RIGHT","#").Replace("LEFT","RIGHT").Replace("#","LEFT").Replace("UP","#").Replace("DOWN","UP").Replace("#","DOWN");static double Lerp(double a,double b,double t)=>a+(Safe(b)-a)*t;static double Safe(double v)=>!double.IsNaN(v)&&!double.IsInfinity(v)?v:0;static double SafeScale(double v)=>!double.IsNaN(v)&&!double.IsInfinity(v)&&v>0?v:1;
 }
}
