using System;
using System.Collections.Generic;
using OpenCvSharp;
using SarmatVisionHold.Core;
using SarmatVisionHold.Vision;

internal static class Program
{
 const int Width=640,Height=480;const double Focal=500,Dt=.05;static readonly DateTime T0=new DateTime(2030,1,1,0,0,0,DateTimeKind.Utc);static int passed;
 static int Main(){var tests=new Action[]{StationaryCamera,TranslationAxesAndScale,AffineTranslationRotationScaleAndMixed,AttitudeOnlyCompensation,DegradedImagesAndDroppedFrames,SharedProcessorStatusAndFiniteValues,AxisConventionMutationGuard};try{foreach(var test in tests){test();passed++;Console.WriteLine("PASS "+test.Method.Name);}Console.WriteLine($"All {passed} offline optical-flow groups passed.");return 0;}catch(Exception e){Console.Error.WriteLine(e);return 1;}}

 static void StationaryCamera(){using(var source=Texture(7))using(var copy=source.Clone())using(var tracker=new OpticalFlowTracker()){First(tracker,source);var f=tracker.Process(copy,T0.AddSeconds(Dt),20,Focal);NotNull(f);True(f.TrackedPoints>=50,"stationary feature count");Near(0,f.RawX,2e-4,"stationary X");Near(0,f.RawY,2e-4,"stationary Y");True(f.Quality>.7,"stationary quality");}}

 static void TranslationAxesAndScale(){var cases=new[]{new Motion(5,0),new Motion(-5,0),new Motion(0,4),new Motion(0,-4),new Motion(5,-4)};foreach(var motion in cases)using(var source=Texture(11))using(var moved=Shift(source,motion.X,motion.Y))using(var tracker=new OpticalFlowTracker()){First(tracker,source);var f=tracker.Process(moved,T0.AddSeconds(Dt),20,Focal);NotNull(f);Near(motion.X/Focal,f.RawX,1.5e-3,$"X scale for {motion}");Near(motion.Y/Focal,f.RawY,1.5e-3,$"Y scale for {motion}");if(motion.X!=0)Eq(Math.Sign(motion.X),Math.Sign(f.RawX),"X sign");if(motion.Y!=0)Eq(Math.Sign(motion.Y),Math.Sign(f.RawY),"Y sign");}}

 static void AttitudeOnlyCompensation(){const double pitch=.16,roll=.12;var px=pitch*Dt*Focal;var py=-roll*Dt*Focal;using(var source=Texture(23))using(var attitudeFrame=Shift(source,px,py))using(var tracker=new OpticalFlowTracker()){First(tracker,source);var f=tracker.Process(attitudeFrame,T0.AddSeconds(Dt),20,Focal);var ok=new AttitudeCompensator().Compensate(f,new TelemetrySample{PitchRate=pitch,RollRate=roll,YawRate=0});True(ok);Near(0,f.CompensatedX,1.5e-3,"pitch-only compensated X");Near(0,f.CompensatedY,1.5e-3,"roll-only compensated Y");}
  using(var source=Texture(29))using(var rotated=Rotate(source,2))using(var tracker=new OpticalFlowTracker()){First(tracker,source);var f=tracker.Process(rotated,T0.AddSeconds(Dt),20,Focal);new AttitudeCompensator().Compensate(f,new TelemetrySample{YawRate=2*Math.PI/180/Dt});Near(0,f.CompensatedX,2e-3,"yaw-only compensated X");Near(0,f.CompensatedY,2e-3,"yaw-only compensated Y");}}
 static void AffineTranslationRotationScaleAndMixed(){foreach(var m in new[]{new Motion(5,0),new Motion(-5,0),new Motion(0,4),new Motion(0,-4)})using(var a=Texture(71))using(var b=Transform(a,m.X,m.Y,0,1))using(var p=new SparseOpticalFlowProcessor()){p.Process(a);var r=p.Process(b);Near(m.X,r.TranslationX,1,"affine X");Near(m.Y,r.TranslationY,1,"affine Y");True(FiniteAll(r));}
  using(var a=Texture(73))using(var cw=Transform(a,0,0,3,1))using(var ccw=Transform(a,0,0,-3,1))using(var p1=new SparseOpticalFlowProcessor())using(var p2=new SparseOpticalFlowProcessor()){p1.Process(a);var r1=p1.Process(cw);p2.Process(a);var r2=p2.Process(ccw);Near(-3,r1.RotationDegrees,.5,"CW sign");Near(3,r2.RotationDegrees,.5,"CCW sign");var o=new MotionClassifierOptions{HysteresisFrames=1};Eq("ROTATING_CW",new TemporalMotionClassifier(o).Update(r1).SmoothedClass);Eq("ROTATING_CCW",new TemporalMotionClassifier(o).Update(r2).SmoothedClass);}
  using(var a=Texture(75))using(var zoom=Transform(a,0,0,0,1.03))using(var p=new SparseOpticalFlowProcessor()){p.Process(a);var r=p.Process(zoom);Near(1.03,r.Scale,.01,"scale");Eq("EXPANDING",new TemporalMotionClassifier(new MotionClassifierOptions{HysteresisFrames=1}).Update(r).SmoothedClass);}
  using(var a=Texture(77))using(var mixed=Transform(a,3,-2,.75,1.009))using(var p=new SparseOpticalFlowProcessor()){p.Process(a);var r=p.Process(mixed);var d=new TemporalMotionClassifier(new MotionClassifierOptions{TranslationThreshold=1,RotationThresholdDegrees=.25,ScaleThreshold=.003,DominanceRatio=1.4,HysteresisFrames=1}).Update(r);Eq("MIXED",d.SmoothedClass);True(FiniteAll(r));}}

 static void DegradedImagesAndDroppedFrames(){double baseline;using(var source=Texture(31))using(var moved=Shift(source,3,2))using(var tracker=new OpticalFlowTracker()){First(tracker,source);baseline=tracker.Process(moved,T0.AddSeconds(Dt),20,Focal).Quality;True(baseline>.5,"baseline quality");}
  using(var source=Texture(31))using(var blurred=Shift(source,3,2))using(var tracker=new OpticalFlowTracker()){Cv2.GaussianBlur(blurred,blurred,new Size(41,41),12);First(tracker,source);var f=tracker.Process(blurred,T0.AddSeconds(Dt),20,Focal);NotNull(f);True(Finite(f.Quality));True(f.Quality<baseline,"blur must lower quality");}
  using(var grassA=Noise(41))using(var grassB=Noise(42))using(var tracker=new OpticalFlowTracker()){First(tracker,grassA);var f=tracker.Process(grassB,T0.AddSeconds(Dt),20,Focal);NotNull(f);True(Finite(f.Quality));True(f.Quality<baseline,"decorrelated grass must lower quality");}
  using(var source=Texture(31))using(var blank=new Mat(Height,Width,MatType.CV_8UC3,Scalar.Black))using(var tracker=new OpticalFlowTracker()){First(tracker,source);var lost=tracker.Process(blank,T0.AddSeconds(Dt),20,Focal);NotNull(lost);True(Finite(lost.Quality));True(lost.Quality<baseline*.2,"lost-frame quality must collapse");var duplicate=tracker.Process(blank,T0.AddSeconds(Dt),20,Focal);True(duplicate==null,"duplicate timestamp is a dropped frame, not an exception");using(var recovered=Texture(31)){var afterDrop=tracker.Process(recovered,T0.AddSeconds(Dt*3),10,Focal);NotNull(afterDrop);True(Finite(afterDrop.Quality));}}}

 static void AxisConventionMutationGuard(){using(var source=Texture(53))using(var moved=Shift(source,6,-5))using(var tracker=new OpticalFlowTracker()){First(tracker,source);var f=tracker.Process(moved,T0.AddSeconds(Dt),20,Focal);True(f.RawX>0,"AXIS CONTRACT: rightward surface motion must be +X; inverted X must fail this test");True(f.RawY<0,"AXIS CONTRACT: upward image motion must be -Y; inverted Y must fail this test");}}
 static void SharedProcessorStatusAndFiniteValues(){var options=new SparseOpticalFlowOptions{MinimumAcceptedPoints=250};using(var source=Texture(61))using(var same=source.Clone())using(var processor=new SparseOpticalFlowProcessor(options)){Eq(FlowTrackingStatus.LOST,processor.Process(source).Status);var stable=processor.Process(same);True(stable.Status==FlowTrackingStatus.OK||stable.Status==FlowTrackingStatus.DEGRADED);True(Finite(stable.MedianX)&&Finite(stable.MedianY)&&Finite(stable.Magnitude)&&Finite(stable.Quality));}using(var source=Texture(61))using(var blur=source.Clone())using(var processor=new SparseOpticalFlowProcessor(options)){Cv2.GaussianBlur(blur,blur,new Size(61,61),20);processor.Process(source);var degraded=processor.Process(blur);True(degraded.Status!=FlowTrackingStatus.OK,"blur must be DEGRADED/LOST");True(Finite(degraded.MedianX)&&Finite(degraded.MedianY)&&Finite(degraded.Magnitude)&&Finite(degraded.Quality));}using(var source=Texture(61))using(var empty=new Mat())using(var processor=new SparseOpticalFlowProcessor(options)){processor.Process(source);var lost=processor.Process(empty);Eq(FlowTrackingStatus.LOST,lost.Status);True(Finite(lost.MedianX)&&Finite(lost.MedianY)&&Finite(lost.Magnitude)&&Finite(lost.Quality));}}

 static void First(OpticalFlowTracker tracker,Mat frame){var first=tracker.Process(frame,T0,20,Focal);True(first==null,"first frame initializes tracker");}
 static Mat Texture(int seed){var m=new Mat(Height,Width,MatType.CV_8UC3,new Scalar(24,28,31));var r=new Random(seed);for(var i=0;i<350;i++){var x=r.Next(8,Width-8);var y=r.Next(8,Height-8);var radius=r.Next(2,6);var color=new Scalar(r.Next(60,256),r.Next(60,256),r.Next(60,256));Cv2.Circle(m,new Point(x,y),radius,color,-1,LineTypes.AntiAlias);}for(var i=0;i<40;i++){var x=r.Next(0,Width-30);var y=r.Next(0,Height-30);Cv2.Rectangle(m,new Rect(x,y,r.Next(8,30),r.Next(8,30)),new Scalar(r.Next(40,220),r.Next(40,220),r.Next(40,220)),1);}return m;}
 static Mat Noise(int seed){var m=new Mat(Height,Width,MatType.CV_8UC3);var r=new Random(seed);var bytes=new byte[Width*Height*3];r.NextBytes(bytes);System.Runtime.InteropServices.Marshal.Copy(bytes,0,m.Data,bytes.Length);Cv2.GaussianBlur(m,m,new Size(5,5),1);return m;}
 static Mat Shift(Mat source,double x,double y){var result=new Mat();using(var matrix=Mat.FromArray(new double[,]{{1d,0d,x},{0d,1d,y}}))Cv2.WarpAffine(source,result,matrix,new Size(Width,Height),InterpolationFlags.Linear,BorderTypes.Reflect101);return result;}
 static Mat Rotate(Mat source,double degrees){var result=new Mat();using(var matrix=Cv2.GetRotationMatrix2D(new Point2f(Width/2f,Height/2f),degrees,1))Cv2.WarpAffine(source,result,matrix,new Size(Width,Height),InterpolationFlags.Linear,BorderTypes.Reflect101);return result;}
 static Mat Transform(Mat source,double x,double y,double degrees,double scale){var result=new Mat();using(var matrix=Cv2.GetRotationMatrix2D(new Point2f(Width/2f,Height/2f),degrees,scale)){matrix.Set(0,2,matrix.At<double>(0,2)+x);matrix.Set(1,2,matrix.At<double>(1,2)+y);Cv2.WarpAffine(source,result,matrix,new Size(Width,Height),InterpolationFlags.Linear,BorderTypes.Reflect101);}return result;}
 readonly struct Motion{public readonly double X,Y;public Motion(double x,double y){X=x;Y=y;}public override string ToString()=>$"({X},{Y})";}
 static bool Finite(double v)=>!double.IsNaN(v)&&!double.IsInfinity(v);static bool FiniteAll(SparseOpticalFlowResult r)=>Finite(r.TranslationX)&&Finite(r.TranslationY)&&Finite(r.RotationDegrees)&&Finite(r.Scale)&&Finite(r.Quality)&&Finite(r.InlierRatio);static void NotNull(object value){True(value!=null,"expected non-null");}static void True(bool value,string message=null){if(!value)throw new Exception(message??"expected true");}static void Eq<T>(T expected,T actual,string message=null){if(!EqualityComparer<T>.Default.Equals(expected,actual))throw new Exception($"{message??"assert"}: expected {expected}, got {actual}");}static void Near(double expected,double actual,double tolerance,string message){if(!Finite(actual)||Math.Abs(expected-actual)>tolerance)throw new Exception($"{message}: expected {expected} +/- {tolerance}, got {actual}");}
}
