using System;using System.Globalization;using System.IO;using Newtonsoft.Json;using SarmatVisionHold.KestrelClient.Control;
namespace SarmatVisionHold.KestrelClient { public sealed class KestrelClientOptions {
 public string Url="ws://127.0.0.1:8765",Output="artifacts/kestrel-live",Config;public bool Preview=false,Headless=true,Reconnect=true,SaveAnnotatedVideo,SaveRawFrames;public int SyncTimeoutMs=500,MaxPending=32;public double MaxDuration=-1;public string LogLevel="Information";public VisionControlOptions Control=new VisionControlOptions();
 public static KestrelClientOptions Parse(string[] a){var o=new KestrelClientOptions();for(int i=0;i<a.Length;i++){var k=a[i].ToLowerInvariant();Func<string> next=()=>i+1<a.Length?a[++i]:throw new ArgumentException("Missing value for "+a[i]);Func<double> num=()=>double.Parse(next(),CultureInfo.InvariantCulture);switch(k){
 case "--url":o.Url=next();break;case "--output":o.Output=next();break;case "--config":case "--control-config":o.Config=next();break;case "--sync-timeout-ms":o.SyncTimeoutMs=int.Parse(next());break;case "--max-pending":o.MaxPending=int.Parse(next());break;case "--max-duration":o.MaxDuration=num();break;case "--log-level":o.LogLevel=next();break;
 case "--control-mode":o.Control.Mode=(VisionControlMode)Enum.Parse(typeof(VisionControlMode),next(),true);break;case "--kp-x":o.Control.KpX=num();break;case "--kp-y":o.Control.KpY=num();break;case "--ki-x":o.Control.KiX=num();break;case "--ki-y":o.Control.KiY=num();break;case "--kd-x":o.Control.KdX=num();break;case "--kd-y":o.Control.KdY=num();break;case "--position-kp-x":o.Control.PositionKpX=num();break;case "--position-kp-y":o.Control.PositionKpY=num();break;case "--max-position-error":o.Control.MaxPositionErrorMeters=num();break;case "--no-position-hold":o.Control.EnablePositionHold=false;break;case "--max-command":o.Control.MaxCommand=num();break;case "--max-integral":o.Control.MaxIntegralContribution=num();break;case "--integral-clamp-x":o.Control.IntegralClampX=num();break;case "--integral-clamp-y":o.Control.IntegralClampY=num();break;case "--integral-leak":o.Control.IntegralLeakPerSecond=num();break;case "--velocity-units":o.Control.VelocityUnits=(VisionVelocityUnits)Enum.Parse(typeof(VisionVelocityUnits),next(),true);break;case "--enable-control-calibration":o.Control.EnableControlCalibration=true;break;
 case "--deadband-flow":case "--deadband-velocity":o.Control.DeadbandVelocity=num();break;case "--max-slew-rate":o.Control.MaxSlewRatePerSecond=num();break;case "--minimum-quality":o.Control.MinimumQuality=num();break;case "--stale-timeout-ms":o.Control.StaleFrameTimeoutMs=int.Parse(next());break;case "--recovery-good-frames":o.Control.RecoveryGoodFrames=int.Parse(next());break;case "--pilot-override-deadband":o.Control.PilotOverrideDeadband=num();break;case "--rotation-reject-threshold":o.Control.RotationRejectThreshold=num();break;
 case "--preview":o.Preview=true;o.Headless=false;break;case "--headless":o.Headless=true;o.Preview=false;break;case "--reconnect":o.Reconnect=true;break;case "--no-reconnect":o.Reconnect=false;break;case "--save-annotated-video":o.SaveAnnotatedVideo=true;break;case "--save-raw-frames":o.SaveRawFrames=true;break;case "--help":case "-h":throw new OperationCanceledException();default:throw new ArgumentException("Unknown option: "+a[i]);}}
 if(!string.IsNullOrWhiteSpace(o.Config)){var loaded=JsonConvert.DeserializeObject<KestrelClientOptions>(File.ReadAllText(o.Config));if(loaded!=null)o=loaded;}if(!Uri.TryCreate(o.Url,UriKind.Absolute,out var uri)||(uri.Scheme!="ws"&&uri.Scheme!="wss"))throw new ArgumentException("--url must be ws:// or wss://");o.MaxPending=Math.Max(2,o.MaxPending);o.SyncTimeoutMs=Math.Max(1,o.SyncTimeoutMs);o.Control.MaxCommand=Math.Max(0,Math.Min(.75,o.Control.MaxCommand));o.Control.MaxIntegralContribution=Math.Max(0,Math.Min(o.Control.MaxCommand,o.Control.MaxIntegralContribution));o.Control.MaxPositionErrorMeters=Math.Max(0,o.Control.MaxPositionErrorMeters);return o;
 } } }
