using System;using System.Diagnostics;using System.Threading;using System.Threading.Tasks;using Newtonsoft.Json;using OpenCvSharp;using SarmatVisionHold.KestrelClient.Control;using SarmatVisionHold.KestrelClient.Models;using SarmatVisionHold.KestrelClient.Networking;using SarmatVisionHold.KestrelClient.Output;using SarmatVisionHold.KestrelClient.Processing;using SarmatVisionHold.Vision;
namespace SarmatVisionHold.KestrelClient { internal static class Program {
 static int Main(string[] args){try{return Run(KestrelClientOptions.Parse(args)).GetAwaiter().GetResult();}catch(OperationCanceledException){Usage();return 0;}catch(Exception e){Console.Error.WriteLine("FATAL: "+e);return 1;}}
 static async Task<int> Run(KestrelClientOptions o){using(var quit=new CancellationTokenSource()){
  Console.CancelKeyPress+=(s,e)=>{e.Cancel=true;quit.Cancel();};if(o.MaxDuration>0)quit.CancelAfter(TimeSpan.FromSeconds(o.MaxDuration));
  var sync=new FrameTelemetrySynchronizer(o.SyncTimeoutMs,o.MaxPending);var decoder=new KdvfFrameDecoder();var parser=new TelemetryMessageParser();var ground=new GroundTruthMotionEstimator();var validator=new MotionValidator();var preview=new PreviewRenderer();var flow=new SparseOpticalFlowProcessor(new SparseOpticalFlowOptions{MaxFeatures=800,QualityLevel=.001,MinimumDistance=4,MinimumAcceptedPoints=8,ForwardBackwardErrorThreshold=3,RansacReprojectionThreshold=3});var classifier=new TemporalMotionClassifier();var controller=new VisionVelocityDampingController(o.Control);var client=new KestrelWebSocketClient(o.Url,o.Reconnect);
  SessionOutput output=null;Guid session=Guid.Empty;uint last=0;ulong lastTime=0;bool paused=false,snapshot=false;
  Action<SynchronizedSample> process=sample=>{using(sample){
   if(sample.Frame.SessionId!=session||sample.Frame.FrameNumber<last||sample.Frame.TimestampUs<lastTime){output?.Dispose();output=new SessionOutput(o.Output,sample.Frame.SessionId);session=sample.Frame.SessionId;flow.Reset();controller.Reset();sync.Reset();}
   var previousTime=lastTime;last=sample.Frame.FrameNumber;lastTime=sample.Frame.TimestampUs;if(paused)return;var sw=Stopwatch.StartNew();SparseOpticalFlowResult f;using(var gray=new Mat())using(var enhanced=new Mat())using(var featureMask=new Mat(sample.Frame.Image.Rows,sample.Frame.Image.Cols,MatType.CV_8UC1,Scalar.White)){Cv2.CvtColor(sample.Frame.Image,gray,ColorConversionCodes.BGR2GRAY);Cv2.EqualizeHist(gray,enhanced);var vehicleTop=(int)Math.Round(featureMask.Rows*.60);Cv2.Rectangle(featureMask,new Rect(0,vehicleTop,featureMask.Cols,featureMask.Rows-vehicleTop),Scalar.Black,-1);f=flow.Process(enhanced,featureMask);}if(f.Status==FlowTrackingStatus.LOST&&output!=null){var lostPath=System.IO.Path.Combine(output.DirectoryPath,"lost-frame.jpg");if(!System.IO.File.Exists(lostPath))Cv2.ImWrite(lostPath,sample.Frame.Image);}var d=classifier.Update(f);var g=ground.Estimate(sample.Telemetry);var v=validator.Validate(f,d,g);
   var dt=previousTime>0&&lastTime>previousTime?(lastTime-previousTime)/1000000d:1d/20;o.Control.CameraMountRotationDegrees=sample.Telemetry.Camera.MountYawRad*180/Math.PI;
   var ci=new VisionControlInput{SessionId=session,FrameNumber=last,TimestampUs=lastTime,DeltaSeconds=dt,TextureFlowX=d.SmoothedX/dt,TextureFlowY=d.SmoothedY/dt,Quality=f.Quality,RotationDegrees=f.RotationDegrees,FrameAgeMs=(DateTime.UtcNow-sample.Frame.ReceivedUtc).TotalMilliseconds,Lost=f.Status==FlowTrackingStatus.LOST,Degraded=f.Status==FlowTrackingStatus.DEGRADED,Paused=sample.Telemetry.State.Paused,OnGround=sample.Telemetry.State.OnGround,Crashed=sample.Telemetry.State.Crashed,PilotRoll=sample.Telemetry.Input?.Axes?.Roll??0,PilotPitch=sample.Telemetry.Input?.Axes?.Pitch??0,AltitudeMeters=Math.Max(0,sample.Telemetry.Position.Y),HorizontalFovDegrees=sample.Telemetry.Camera.FovDegrees,ImageWidth=sample.Telemetry.Camera.Width,ImageHeight=sample.Telemetry.Camera.Height,YawDegrees=sample.Telemetry.Attitude.YawRad*180/Math.PI};
   var co=o.Control.EnableControlCalibration?controller.CalibrationOutput(ci):controller.Update(ci);if(controller.Mode==VisionControlMode.CONTROL||o.Control.EnableControlCalibration){var message=controller.Message(ci,co);client.SendTextAsync(JsonConvert.SerializeObject(message),quit.Token).GetAwaiter().GetResult();}sw.Stop();output?.Write(sample,f,d,g,v,sw.Elapsed.TotalMilliseconds,sync.Counters);
   if(o.SaveRawFrames)Cv2.ImWrite(System.IO.Path.Combine(output.DirectoryPath,"snapshots",$"raw-{last:D8}.jpg"),sample.Frame.Image);if(snapshot){output.SaveSnapshot(sample.Frame.Image,last);snapshot=false;}
   if(o.Preview){var annotated=sample.Frame.Image.Clone();var key=preview.Show(annotated,f,d,g,v,last,sample.Telemetry.SimulationTimeSeconds,sample.NetworkLatencyMs,sw.Elapsed.TotalMilliseconds,sync.Counters,client.State,controller.Mode,co,controller.SaturationPercentage);if(key==27||key=='q'||key=='Q')quit.Cancel();else if(key==' ')paused=!paused;else if(key=='s'||key=='S')snapshot=true;else if(key=='v'||key=='V')preview.Vectors=!preview.Vectors;else if(key=='t'||key=='T')preview.Telemetry=!preview.Telemetry;else if(key=='c'||key=='C')controller.SetMode(controller.Mode==VisionControlMode.CONTROL?VisionControlMode.DIAGNOSTICS:VisionControlMode.CONTROL);else if(key=='o'||key=='O')controller.SetMode(VisionControlMode.OFF);annotated.Dispose();}
   Console.Write($"\r#{last} {co.State,-12} flow=({ci.TextureFlowX,7:F1},{ci.TextureFlowY,7:F1}) P=({co.PTermX,6:F3},{co.PTermY,6:F3}) I=({co.ITermX,6:F3},{co.ITermY,6:F3}) D=({co.DTermX,6:F3},{co.DTermY,6:F3}) cmd=({co.RollCommand,6:F3},{co.PitchCommand,6:F3}) ack={co.AppliedSequence}/{controller.LastSentSequence} sat={controller.SaturationPercentage:F1}%   ");
  }};
  client.BinaryReceived+=bytes=>{if(decoder.TryDecode(bytes,out var f,out var error)){var s=sync.Add(f);if(s!=null)process(s);}else Console.Error.WriteLine("\nKDVF: "+error);};
  client.TextReceived+=json=>{VisionControlStatus status;if(VisionControlStatus.TryParse(json,out status)){controller.UpdateAcknowledgement(status);if(!o.Control.EnableControlCalibration&&controller.Mode!=VisionControlMode.OFF){var requested=status.ControllerEnabled?VisionControlMode.CONTROL:VisionControlMode.DIAGNOSTICS;if(controller.Mode!=requested){controller.SetMode(requested);Console.WriteLine("\nKestrel requested "+requested);}}return;}if(parser.TryParse(json,out var t,out var error)){var s=sync.Add(t);if(s!=null)process(s);}else if(json.Contains("\"type\":\"telemetry\""))Console.Error.WriteLine("\nTelemetry: "+error);};
  client.Connected+=()=>{Console.WriteLine("Connected to "+o.Url);flow.Reset();controller.Reset();sync.Reset();if(controller.Mode==VisionControlMode.DIAGNOSTICS){controller.SetMode(VisionControlMode.CONTROL);Console.WriteLine("Control producer armed; Kestrel remains the application gate");}};client.Disconnected+=()=>{controller.ExplicitRelease("disconnected");Console.WriteLine("\nDISCONNECTED; correction released");};
  try{await client.RunAsync(quit.Token);}finally{controller.ExplicitRelease("shutdown");output?.Dispose();flow.Dispose();preview.Close();}return 0;
 }}
 static void Usage()=>Console.WriteLine("SarmatVisionHold.KestrelClient --control-mode off|diagnostics|control [--kp-x N --kp-y N --ki-x N --ki-y N --position-kp-x N --position-kp-y N --max-position-error N --no-position-hold --max-command .75 --max-integral .35 --velocity-units pxps|mps --deadband-velocity N --max-slew-rate N]");
 } }
