import { useEffect, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, BatteryCharging, BatteryLow, Save, ShieldAlert } from "lucide-react";
import { api } from "../api";
import { useI18n } from "../i18n";
export function SettingsPage() {
  const qc=useQueryClient(); const { t }=useI18n(); const query=useQuery({queryKey:["thresholds"],queryFn:api.thresholds}); const [saved,setSaved]=useState(false);
  const mutation=useMutation({mutationFn:api.updateThresholds,onSuccess:()=>{qc.invalidateQueries({queryKey:["thresholds"]});setSaved(true);setTimeout(()=>setSaved(false),2500)}});
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);mutation.mutate({warningCellDeltaV:Number(d.get("warning")),dangerCellDeltaV:Number(d.get("danger")),chargedThresholdPercent:Number(d.get("charged")),dischargedThresholdPercent:Number(d.get("discharged"))})};
  return <div className="page settings-page"><section className="hero-row"><div><span className="eyebrow">{t("settings.eyebrow")}</span><h1>{t("settings.title")}</h1><p>{t("settings.description")}</p></div></section><section className="panel settings-card"><form onSubmit={submit} key={`${query.data?.warningCellDeltaV}-${query.data?.chargedThresholdPercent}-${query.data?.dischargedThresholdPercent}`}><div className="threshold-field warning"><span><AlertTriangle/></span><label>{t("settings.warning")}<small>{t("settings.warningHelp")}</small><div><input name="warning" type="number" step="0.01" min="0.01" defaultValue={(query.data?.warningCellDeltaV ?? .1).toFixed(2)}/><b>{t("common.volts")}</b></div></label></div><div className="threshold-field danger"><span><ShieldAlert/></span><label>{t("settings.danger")}<small>{t("settings.dangerHelp")}</small><div><input name="danger" type="number" step="0.01" min="0.02" defaultValue={(query.data?.dangerCellDeltaV ?? .2).toFixed(2)}/><b>{t("common.volts")}</b></div></label></div><div className="threshold-field charge-state"><span><BatteryCharging/></span><label>{t("settings.charged")}<small>{t("settings.chargedHelp")}</small><div><input name="charged" type="number" step="1" min="51" max="100" defaultValue={query.data?.chargedThresholdPercent ?? 90}/><b>%</b></div></label></div><div className="threshold-field charge-state"><span><BatteryLow/></span><label>{t("settings.discharged")}<small>{t("settings.dischargedHelp")}</small><div><input name="discharged" type="number" step="1" min="0" max="50" defaultValue={query.data?.dischargedThresholdPercent ?? 50}/><b>%</b></div></label></div>{mutation.error&&<p className="form-error">{t("errors.generic")}</p>}<div className="settings-footer"><p>{t("settings.historyNote")}</p><button className="button primary"><Save size={17}/>{saved?t("settings.saved"):t("settings.save")}</button></div></form></section></div>;
}
