using System;
using System.Collections.Generic;
using SarmatVisionHold.Core;

internal static class Program
{
 static int passed;
 static int Main(){var tests=new Action[]{RcThresholds,RcHysteresis,RcDebounceAndChatter,RcInversionMissingStaleAndEvents,StateTransitions,StateReadinessAndForbiddenTransitions,StateFailsafes,FreshnessQualityAndHeight,SettingsBoundaries,GroundVelocity,AttitudeCompensation,FailsafeCoordinator};try{foreach(var t in tests){t();passed++;Console.WriteLine("PASS "+t.Method.Name);}Console.WriteLine($"All {passed} SarmatVisionHold unit-test groups passed.");return 0;}catch(Exception e){Console.Error.WriteLine(e);return 1;}}

 static VisionHoldSettings Settings()=>new VisionHoldSettings{RcEnableThreshold=1700,RcDisableThreshold=1300,RcDebounceMs=100,RcStaleMs=500,MaxFrameAgeMs=200,MinimumFps=10,MinimumTrackedPoints=20,MinimumFlowQuality=.4,DiagnosticsOnly=false,EnableLiveControl=true};
 static void RcThresholds(){foreach(var c in new[]{Tuple.Create(1699,false),Tuple.Create(1700,true),Tuple.Create(2200,true)}){var s=Settings();s.RcDebounceMs=0;var k=new FakeClock();var r=new RcSwitchListener(s,k);Sample(r,k,c.Item1);Eq(c.Item2,r.State,"enable boundary");}var ss=Settings();ss.RcDebounceMs=0;var cc=new FakeClock();var rr=new RcSwitchListener(ss,cc);Sample(rr,cc,1800);True(rr.State);foreach(var pwm in new[]{1301,1500,1699}){Sample(rr,cc,pwm);True(rr.State,"hysteresis must retain ON");}Sample(rr,cc,1300);False(rr.State);}
 static void RcHysteresis(){var s=Settings();s.RcDebounceMs=0;var c=new FakeClock();var r=new RcSwitchListener(s,c);foreach(var pwm in new[]{1301,1500,1699}){Sample(r,c,pwm);False(r.State,"middle range retains OFF");}Sample(r,c,1800);True(r.State);foreach(var pwm in new[]{1699,1500,1301}){Sample(r,c,pwm);True(r.State,"middle range retains ON");}}
 static void RcDebounceAndChatter(){var s=Settings();var c=new FakeClock();var r=new RcSwitchListener(s,c);r.Update(1800);c.Advance(99);r.Update(1800);False(r.State);c.Advance(1);r.Update(1800);True(r.State);var transitions=0;r.StateChanged+=x=>transitions++;for(var i=0;i<20;i++){c.Advance(20);r.Update(i%2==0?1200:1800);}True(r.State,"chatter must not flip state");Eq(0,transitions,"chatter events");}
 static void RcInversionMissingStaleAndEvents(){var s=Settings();s.RcDebounceMs=0;s.RcInverted=true;var c=new FakeClock();var r=new RcSwitchListener(s,c);var events=new List<bool>();r.StateChanged+=events.Add;Sample(r,c,1200);True(r.State);for(var i=0;i<5;i++)Sample(r,c,1200);Eq(1,events.Count,"duplicate ON events");Sample(r,c,1800);False(r.State);Eq(2,events.Count);Sample(r,c,0);False(r.State,"missing channel OFF");var normal=Settings();normal.RcDebounceMs=0;var r2=new RcSwitchListener(normal,c);Sample(r2,c,1800);True(r2.State);c.Advance(normal.RcStaleMs);r2.CheckStale();True(r2.State,"exact stale boundary is fresh");c.Advance(1);r2.CheckStale();False(r2.State);}

 static HealthSnapshot H(bool request=false,bool stream=true,bool frame=true,bool flow=true,bool height=true,bool mav=true,bool rc=true,bool live=true,string reason=null)=>new HealthSnapshot{Requested=request,PilotRequested=request,StreamWorking=stream,FramesFresh=frame,FlowGood=flow,HeightValid=height,MavlinkActive=mav,RcFresh=rc,LiveAllowed=live,BlockReason=reason};
 static void Warm(VisionHoldStateMachine m,bool request=false){for(var i=0;i<3;i++)m.Update(H(request));}
 static void StateTransitions(){var m=new VisionHoldStateMachine(2);Eq(VisionHoldState.Disabled,m.State);m.Update(H());Eq(VisionHoldState.WarmingUp,m.State);m.Update(H());Eq(VisionHoldState.Ready,m.State);m.Update(H(true));Eq(VisionHoldState.Active,m.State);m.Update(H(true,flow:false,reason:"quality"));Eq(VisionHoldState.Lost,m.State);m.Update(H(false));Eq(VisionHoldState.WarmingUp,m.State);m.Update(H(false));Eq(VisionHoldState.Ready,m.State);m.Update(H(true,stream:false,reason:"video"));Eq(VisionHoldState.Degraded,m.State);m.Update(H(false,stream:false,reason:"video"));Eq(VisionHoldState.Disabled,m.State);}
 static void StateReadinessAndForbiddenTransitions(){foreach(var bad in new Func<HealthSnapshot>[] {()=>H(true,stream:false,reason:"video"),()=>H(true,frame:false,reason:"frame"),()=>H(true,flow:false,reason:"flow"),()=>H(true,height:false,reason:"height"),()=>H(true,mav:false,reason:"mav"),()=>H(true,rc:false,reason:"rc")}){var m=new VisionHoldStateMachine(2);m.Update(bad());Ne(VisionHoldState.Active,m.State,"direct activation forbidden");}var d=new VisionHoldStateMachine(1);d.Update(H(true,live:false));Eq(VisionHoldState.Ready,d.State);var active=new VisionHoldStateMachine(1);active.Update(H(true));Eq(VisionHoldState.Active,active.State);active.Update(H(false));Ne(VisionHoldState.Active,active.State,"manual OFF priority");var lost=new VisionHoldStateMachine(1);lost.Update(H(true));lost.Update(H(true,flow:false,reason:"flow"));Eq(VisionHoldState.Lost,lost.State);for(var i=0;i<5;i++)lost.Update(H(true));Eq(VisionHoldState.Lost,lost.State,"held request may not auto-reactivate");lost.Update(H(false));lost.Update(H(true));Eq(VisionHoldState.Active,lost.State,"new OFF/ON confirmation");}
 static void StateFailsafes(){foreach(var c in new[]{Tuple.Create("Video lost",H(true,stream:false,reason:"Video lost")),Tuple.Create("MAVLink unavailable",H(true,mav:false,reason:"MAVLink unavailable")),Tuple.Create("Height invalid",H(true,height:false,reason:"Height invalid")),Tuple.Create("Flow quality zero",H(true,flow:false,reason:"Flow quality zero")),Tuple.Create("RC stale",H(true,rc:false,reason:"RC stale"))}){var m=new VisionHoldStateMachine(1);m.Update(H(true));m.Update(c.Item2);Eq(VisionHoldState.Lost,m.State);Contains(c.Item1,m.Reason);}}

 static void FreshnessQualityAndHeight(){var s=Settings();var c=new FakeClock();var t=new TelemetrySample{TimestampUtc=c.UtcNow,LinkActive=true,HeightMeters=2,HeightValid=true,RcPwm=1800};var f=new FlowSample{TimestampUtc=c.UtcNow,Fps=10,TrackedPoints=20,Quality=.4,FrameAgeMs=200};var h=HealthEvaluator.Evaluate(true,true,true,f,t,s,c);True(h.FramesFresh);True(h.FlowGood);True(h.HeightValid);c.Advance(201);h=HealthEvaluator.Evaluate(true,true,true,f,t,s,c);False(h.FramesFresh,"stale frame");c.Set(t.TimestampUtc.AddMilliseconds(s.RcStaleMs+1));h=HealthEvaluator.Evaluate(true,true,true,new FlowSample{TimestampUtc=c.UtcNow,Fps=10,TrackedPoints=20,Quality=.4,FrameAgeMs=0},t,s,c);False(h.RcFresh,"stale telemetry");foreach(var q in new[]{new FlowSample{Fps=9.99,TrackedPoints=20,Quality=.4,FrameAgeMs=0},new FlowSample{Fps=10,TrackedPoints=19,Quality=.4,FrameAgeMs=0},new FlowSample{Fps=10,TrackedPoints=20,Quality=.399,FrameAgeMs=0},new FlowSample{Fps=double.NaN,TrackedPoints=20,Quality=.4,FrameAgeMs=0},new FlowSample{Fps=10,TrackedPoints=20,Quality=double.PositiveInfinity,FrameAgeMs=0},new FlowSample{Fps=10,TrackedPoints=20,Quality=.4,FrameAgeMs=-1}})False(FlowQualityEstimator.Pass(q,s));foreach(var value in new[]{0d,-1,double.NaN,double.PositiveInfinity,double.NegativeInfinity})False(HealthEvaluator.ValidHeight(value));True(HealthEvaluator.ValidHeight(double.Epsilon));}
 static void SettingsBoundaries(){var cases=new[]{new VisionHoldSettings{RcChannel=-1,RcEnableThreshold=9999,RcDisableThreshold=9999,RcDebounceMs=-1,RcStaleMs=-1,MaxFrameAgeMs=-1,MinimumFps=double.NaN,MinimumTrackedPoints=-1,MinimumFlowQuality=double.PositiveInfinity,CameraFocalLengthPixels=0,HorizontalFovDegrees=180,FrameWidth=0,FrameHeight=-1,MaximumGroundSpeed=double.NaN,MaximumImuRate=double.PositiveInfinity},new VisionHoldSettings{RcChannel=99,RcEnableThreshold=-1,RcDisableThreshold=-1,RcDebounceMs=99999,RcStaleMs=999999,MaxFrameAgeMs=99999,MinimumFps=-1,MinimumTrackedPoints=99999,MinimumFlowQuality=-1,CameraFocalLengthPixels=double.NaN,HorizontalFovDegrees=-1,FrameWidth=-1,FrameHeight=0,MaximumGroundSpeed=-1,MaximumImuRate=-1}};foreach(var s in cases){s.Normalize();True(s.RcChannel>=1&&s.RcChannel<=18);True(s.RcDisableThreshold<s.RcEnableThreshold);True(s.RcDebounceMs>=0&&s.RcDebounceMs<=10000);True(s.RcStaleMs>=100&&s.RcStaleMs<=60000);True(Finite(s.MinimumFps)&&s.MinimumFps>=0);True(s.MinimumTrackedPoints>=0&&s.MinimumTrackedPoints<=10000);True(Finite(s.MinimumFlowQuality)&&s.MinimumFlowQuality>=0&&s.MinimumFlowQuality<=1);True(s.FrameWidth>0&&s.FrameHeight>0);True(Finite(s.MaximumGroundSpeed)&&s.MaximumGroundSpeed>=0);}}

 static void GroundVelocity(){var e=new GroundVelocityEstimator(5);var f=new FlowSample{Dt=1,CompensatedX=0,CompensatedY=0};var t=new TelemetrySample{HeightValid=true,HeightMeters=2};True(e.Estimate(f,t));Near(0,f.VelocityX);Near(0,f.VelocityY);f.CompensatedX=.5;f.CompensatedY=-.25;True(e.Estimate(f,t));Near(1,f.VelocityX);Near(-.5,f.VelocityY);t.HeightMeters=4;e.Estimate(f,t);Near(2,f.VelocityX,"height scale");var p=new FlowSample();True(e.EstimatePixels(p,100,-50,1,2,90,1000,500));Near(.4,p.VelocityX);Near(-.2,p.VelocityY);foreach(var bad in new[]{0d,-1,double.NaN,double.PositiveInfinity}){var x=new FlowSample{VelocityX=3,VelocityY=3};False(e.EstimatePixels(x,1,1,bad,2,90,100,100));FiniteZero(x);}foreach(var fov in new[]{0d,-1,180,double.NaN,double.PositiveInfinity}){var x=new FlowSample();False(e.EstimatePixels(x,1,1,1,2,fov,100,100));FiniteZero(x);}var sat=new FlowSample{Dt=.01,CompensatedX=100,CompensatedY=-100};e.Estimate(sat,new TelemetrySample{HeightValid=true,HeightMeters=100});Near(5,sat.VelocityX);Near(-5,sat.VelocityY);}
 static void AttitudeCompensation(){var f=new FlowSample{RawX=.2,RawY=-.1,Dt=.5};var c=new AttitudeCompensator(10);True(c.Compensate(f,new TelemetrySample()));Near(.2,f.CompensatedX);Near(-.1,f.CompensatedY);f=new FlowSample{RawX=0,RawY=0,Dt=1};c.Compensate(f,new TelemetrySample{PitchRate=1,RollRate=2});Near(-1,f.CompensatedX,"pitch sign");Near(2,f.CompensatedY,"roll sign");f=new FlowSample{RawX=1,RawY=0,Dt=Math.PI/2};c.Compensate(f,new TelemetrySample{YawRate=1});Near(0,f.CompensatedX,1e-8,"yaw rotation");Near(-1,f.CompensatedY,1e-8,"yaw sign");foreach(var bad in new[]{double.NaN,double.PositiveInfinity,11d,-11d}){f=new FlowSample{RawX=.3,RawY=.4,Dt=1};False(c.Compensate(f,new TelemetrySample{RollRate=bad}));Near(.3,f.CompensatedX);Near(.4,f.CompensatedY);True(Finite(f.CompensatedX)&&Finite(f.CompensatedY));}}

 static void FailsafeCoordinator(){foreach(var c in new[]{Tuple.Create("video",H(true,stream:false,reason:"video")),Tuple.Create("mav",H(true,mav:false,reason:"mav")),Tuple.Create("rc",H(true,rc:false,reason:"rc")),Tuple.Create("height",H(true,height:false,reason:"height")),Tuple.Create("quality",H(true,flow:false,reason:"quality"))}){var m=new VisionHoldStateMachine(1);var p=new FakePublisher();var fb=new FakeFallback();var co=new FlowSafetyCoordinator(m,p,fb);co.Tick(H(true),new FlowSample(),new TelemetrySample());Eq(1,p.Count);co.Tick(c.Item2,new FlowSample(),new TelemetrySample());Eq(VisionHoldState.Lost,m.State);Eq(1,p.Count,"publishing stopped");Eq(1,fb.Count);Contains(c.Item1,m.Reason);}var mt=new VisionHoldStateMachine(1);var pt=new FakePublisher();var ft=new FakeFallback();var ct=new FlowSafetyCoordinator(mt,pt,ft);ct.Tick(H(true),new FlowSample(),new TelemetrySample());ct.TrackerFailed(new InvalidOperationException());Eq(VisionHoldState.Lost,mt.State);Contains("Tracker exception",mt.Reason);Eq(1,pt.Count);var mp=new VisionHoldStateMachine(1);var pp=new FakePublisher{Throw=true};var fp=new FakeFallback();var cp=new FlowSafetyCoordinator(mp,pp,fp);cp.Tick(H(true),new FlowSample(),new TelemetrySample());Eq(VisionHoldState.Lost,mp.State);Contains("Publisher exception",mp.Reason);Eq(1,fp.Count);var ms=new VisionHoldStateMachine(1);var ps=new FakePublisher();var fs=new FakeFallback();var cs=new FlowSafetyCoordinator(ms,ps,fs);cs.Tick(H(true),new FlowSample(),new TelemetrySample());cs.Stop();Eq(VisionHoldState.Lost,ms.State);Contains("Plugin stopped",ms.Reason);Eq(1,ps.Count);Eq(1,fs.Count);}

 static void Sample(RcSwitchListener r,FakeClock c,int pwm){r.Update(pwm);c.Advance(1);r.Update(pwm);}
 sealed class FakeClock:IClock{DateTime now=new DateTime(2030,1,1,0,0,0,DateTimeKind.Utc);public DateTime UtcNow=>now;public void Advance(int ms){now=now.AddMilliseconds(ms);}public void Set(DateTime value){now=value;}}
 sealed class FakePublisher:IFlowPublisher{public int Count;public bool Throw;public void Publish(FlowSample f,TelemetrySample t){if(Throw)throw new InvalidOperationException();Count++;}}
 sealed class FakeFallback:IFallbackAction{public int Count;public string Reason;public void Enter(string reason){Count++;Reason=reason;}}
 static bool Finite(double v)=>!double.IsNaN(v)&&!double.IsInfinity(v);static void FiniteZero(FlowSample f){True(Finite(f.VelocityX)&&Finite(f.VelocityY));Near(0,f.VelocityX);Near(0,f.VelocityY);}static void Eq<T>(T e,T a,string m=null){if(!EqualityComparer<T>.Default.Equals(e,a))throw new Exception($"{m??"assert"}: expected {e}, got {a}");}static void Ne<T>(T e,T a,string m=null){if(EqualityComparer<T>.Default.Equals(e,a))throw new Exception($"{m??"assert"}: value must not be {e}");}static void True(bool v,string m=null){if(!v)throw new Exception(m??"expected true");}static void False(bool v,string m=null)=>True(!v,m??"expected false");static void Near(double e,double a,double eps=1e-9,string m=null){if(!Finite(a)||Math.Abs(e-a)>eps)throw new Exception($"{m??"near"}: expected {e}, got {a}");}static void Near(double e,double a,string m)=>Near(e,a,1e-9,m);static void Contains(string part,string value){if(value==null||value.IndexOf(part,StringComparison.OrdinalIgnoreCase)<0)throw new Exception($"'{value}' does not contain '{part}'");}
}
