using System;using System.Collections.Generic;using System.Linq;using SarmatVisionHold.KestrelClient.Models;
namespace SarmatVisionHold.KestrelClient.Networking {
 public sealed class SynchronizationCounters { public long Matched,FrameWithoutTelemetry,TelemetryWithoutFrame,TimestampMismatch,DuplicateFrame,DuplicateTelemetry,OutOfOrder; }
 public sealed class FrameTelemetrySynchronizer { readonly Dictionary<string,Entry> pending=new Dictionary<string,Entry>();readonly TimeSpan timeout;readonly int max;uint? lastFrame;Guid session;public SynchronizationCounters Counters{get;}=new SynchronizationCounters();public FrameTelemetrySynchronizer(int timeoutMs=500,int maxPending=32){timeout=TimeSpan.FromMilliseconds(timeoutMs);max=Math.Max(2,maxPending);}
  public SynchronizedSample Add(KestrelFrame f){Expire();Track(f.SessionId,f.FrameNumber);var e=Get(f.SessionId,f.FrameNumber);if(e.Frame!=null){Counters.DuplicateFrame++;f.Dispose();return null;}e.Frame=f;return Match(e);}public SynchronizedSample Add(KestrelTelemetry t){Expire();Track(t.SessionId,t.FrameNumber);var e=Get(t.SessionId,t.FrameNumber);if(e.Telemetry!=null){Counters.DuplicateTelemetry++;return null;}e.Telemetry=t;return Match(e);}
  Entry Get(Guid id,uint n){var k=Key(id,n);if(!pending.TryGetValue(k,out var e)){while(pending.Count>=max)Drop(pending.OrderBy(x=>x.Value.Created).First().Key);pending[k]=e=new Entry{Key=k,Created=DateTime.UtcNow};}return e;}SynchronizedSample Match(Entry e){if(e.Frame==null||e.Telemetry==null)return null;pending.Remove(e.Key);if(e.Frame.TimestampUs!=e.Telemetry.TimestampUs){Counters.TimestampMismatch++;e.Frame.Dispose();return null;}Counters.Matched++;return new SynchronizedSample{Frame=e.Frame,Telemetry=e.Telemetry};}
  void Track(Guid id,uint n){if(session!=id){session=id;lastFrame=null;}else if(lastFrame.HasValue&&n<lastFrame)Counters.OutOfOrder++;if(!lastFrame.HasValue||n>lastFrame)lastFrame=n;}void Expire(){foreach(var k in pending.Where(x=>DateTime.UtcNow-x.Value.Created>timeout).Select(x=>x.Key).ToArray())Drop(k);}void Drop(string k){var e=pending[k];pending.Remove(k);if(e.Frame!=null){Counters.FrameWithoutTelemetry++;e.Frame.Dispose();}if(e.Telemetry!=null)Counters.TelemetryWithoutFrame++;}public void Reset(){foreach(var k in pending.Keys.ToArray())Drop(k);lastFrame=null;session=Guid.Empty;}static string Key(Guid id,uint n)=>id.ToString("N")+":"+n;sealed class Entry{public string Key;public DateTime Created;public KestrelFrame Frame;public KestrelTelemetry Telemetry;}
 }
}
