using System;using System.Reflection;using SarmatVisionHold.Core;
namespace SarmatVisionHold.Integration
{
 public sealed class MissionPlannerVehicleGateway:IVehicleGateway
 { private readonly Func<object> state;private readonly Func<object> port;public MissionPlannerVehicleGateway(Func<object>s,Func<object>p){state=s;port=p;}
  public TelemetrySample ReadTelemetry(int channel){var cs=state();var stamp=Date(cs,"datetime");if(stamp==default(DateTime))stamp=Date(cs,"lastupdate");var age=stamp==default(DateTime)?TimeSpan.MaxValue:DateTime.UtcNow-stamp.ToUniversalTime();var alt=D(cs,"alt");return new TelemetrySample{TimestampUtc=stamp,LinkActive=port()!=null&&age.TotalSeconds<2,RollRate=D(cs,"gyro_x"),PitchRate=D(cs,"gyro_y"),HeightMeters=Math.Max(0,alt),HeightValid=alt>0&&age.TotalSeconds<2,FlightMode=S(cs,"mode"),RcPwm=(int)D(cs,"ch"+channel+"in")};}
  public string CurrentMode=>S(state(),"mode");public int CurrentEkfSourceSet=>1;
  public bool SetMode(string mode)=>InvokeBool(port(),"setMode",mode);
  public bool SetEkfSourceSet(int set){return InvokeCommand(port(),42007,set,0,0,0,0,0,0);}
  public bool PublishOpticalFlow(FlowSample f,TelemetrySample t){try{var msg=new MAVLink.mavlink_optical_flow_rad_t{time_usec=(ulong)(DateTime.UtcNow.Ticks/10),sensor_id=0,integration_time_us=(uint)Math.Max(1,f.Dt*1000000),integrated_x=(float)f.CompensatedX,integrated_y=(float)f.CompensatedY,integrated_xgyro=(float)(t.RollRate*f.Dt),integrated_ygyro=(float)(t.PitchRate*f.Dt),integrated_zgyro=0,time_delta_distance_us=(uint)Math.Max(1,f.Dt*1000000),distance=(float)t.HeightMeters,temperature=0,quality=(byte)Math.Max(0,Math.Min(255,f.Quality*255))};var p=port();foreach(var candidate in p?.GetType().GetMethods(BindingFlags.Instance|BindingFlags.Public)??new MethodInfo[0])if(candidate.Name=="sendPacket"){var m=candidate.IsGenericMethodDefinition?candidate.MakeGenericMethod(msg.GetType()):candidate;var a=m.GetParameters().Length==3?new object[]{msg,(byte)0,(byte)0}:m.GetParameters().Length==1?new object[]{msg}:null;if(a!=null){m.Invoke(p,a);return true;}}return false;}catch{return false;}}
  static double D(object o,string n){try{var v=Member(o,n);return v==null?0:Convert.ToDouble(v);}catch{return 0;}}static DateTime Date(object o,string n){try{var v=Member(o,n);return v is DateTime d?d:default(DateTime);}catch{return default(DateTime);}}static string S(object o,string n)=>Convert.ToString(Member(o,n));static object Member(object o,string n){if(o==null)return null;var f=BindingFlags.Instance|BindingFlags.Public|BindingFlags.IgnoreCase;return o.GetType().GetProperty(n,f)?.GetValue(o,null)??o.GetType().GetField(n,f)?.GetValue(o);}static bool InvokeBool(object o,string n,params object[] a){try{var methods=o?.GetType().GetMethods(BindingFlags.Instance|BindingFlags.Public);if(methods==null)return false;foreach(var m in methods)if(m.Name==n&&m.GetParameters().Length==a.Length){m.Invoke(o,a);return true;}}catch{}return false;}static bool InvokeCommand(object o,int command,params float[] p){try{foreach(var m in o?.GetType().GetMethods(BindingFlags.Instance|BindingFlags.Public)??new MethodInfo[0])if(m.Name=="doCommand"){var args=m.GetParameters();if(args.Length<8)continue;var values=new object[args.Length];values[0]=Enum.ToObject(args[0].ParameterType,command);for(int i=1;i<8;i++)values[i]=Convert.ChangeType(p[i-1],args[i].ParameterType);for(int i=8;i<values.Length;i++)values[i]=args[i].HasDefaultValue?args[i].DefaultValue:false;m.Invoke(o,values);return true;}}catch{}return false;}
 }
}
