using System;using SarmatAltitudeAssist.Core;
sealed class Clock:IClock{public DateTime UtcNow{get;set;}=new DateTime(2026,1,1,0,0,0,DateTimeKind.Utc);public void Ms(int n){UtcNow=UtcNow.AddMilliseconds(n);}}
sealed class Source:ITelemetrySource{public TelemetrySnapshot Value=new TelemetrySnapshot{TimestampUtc=new DateTime(2026,1,1,0,0,0,DateTimeKind.Utc),Connected=true,HeartbeatHealthy=true,Armed=true,Airborne=true,AltitudeValid=true,AltitudeMeters=100,StickNormalized=.5,FlightMode="LOITER",AltitudeSource="fake"};public TelemetrySnapshot Read(){return Value;}}
sealed class Output:IVerticalControlOutput{readonly Clock c;public Output(Clock x){c=x;}public double LastCommand{get;private set;}public DateTime LastUpdateUtc{get;private set;}public void Apply(double x){LastCommand=x;LastUpdateUtc=c.UtcNow;}public void Release(){LastCommand=0;LastUpdateUtc=c.UtcNow;}}
static class Program
{static int passed,failed;static void A(bool x,string n){if(x){passed++;Console.WriteLine("PASS "+n);}else{failed++;Console.WriteLine("FAIL "+n);}}static GestureDirection Pulse(TripleStickGestureRecognizer g,Clock c,double v){g.Update(.5);c.Ms(80);g.Update(v);c.Ms(100);return g.Update(.5);}static void Main(){GestureTests();ControllerTests();IntegrationTests();Console.WriteLine($"{passed} passed, {failed} failed");Environment.ExitCode=failed==0?0:1;}
 static void GestureTests(){var s=new AltitudeAssistSettings();var c=new Clock();var g=new TripleStickGestureRecognizer(s,c);A(Pulse(g,c,1)==GestureDirection.None,"up pulse 1");A(Pulse(g,c,1)==GestureDirection.None,"up pulse 2");A(Pulse(g,c,1)==GestureDirection.Up,"triple up");g=new TripleStickGestureRecognizer(s,c);Pulse(g,c,0);Pulse(g,c,0);A(Pulse(g,c,0)==GestureDirection.Down,"triple down");g=new TripleStickGestureRecognizer(s,c);Pulse(g,c,1);Pulse(g,c,0);A(Pulse(g,c,1)==GestureDirection.None,"mixed rejected");g=new TripleStickGestureRecognizer(s,c);g.Update(.5);g.Update(1);c.Ms(600);A(g.Update(.5)==GestureDirection.None,"long hold rejected");g=new TripleStickGestureRecognizer(s,c);Pulse(g,c,1);c.Ms(1600);A(Pulse(g,c,1)==GestureDirection.None,"timeout resets");}
 static Tuple<AltitudeAssistController,Source,Output,Clock> Rig(double alt=100){var c=new Clock();var s=new Source();s.Value.AltitudeMeters=alt;s.Value.TimestampUtc=c.UtcNow;var o=new Output(c);var x=new AltitudeAssistController(new AltitudeAssistSettings(),s,o,c);x.Tick();return Tuple.Create(x,s,o,c);}
 static void Step(Tuple<AltitudeAssistController,Source,Output,Clock> r,double alt,int ms=50){r.Item4.Ms(ms);r.Item2.Value.TimestampUtc=r.Item4.UtcNow;r.Item2.Value.AltitudeMeters=alt;r.Item1.Tick();}
 static void ControllerTests(){var r=Rig();r.Item1.Start(GestureDirection.Up);A(r.Item1.State==AssistState.CLIMBING,"climb starts");Step(r,480);var far=Math.Abs(r.Item1.DesiredCommand);Step(r,497);A(Math.Abs(r.Item1.DesiredCommand)<far,"climb slows");Step(r,499);A(r.Item1.State==AssistState.HOLD&&r.Item3.LastCommand==0,"target releases");r=Rig(500);r.Item1.Start(GestureDirection.Down);A(r.Item1.State==AssistState.DESCENDING,"descent starts");Step(r,51);A(r.Item1.State==AssistState.HOLD,"descent target");r=Rig();r.Item1.Start(GestureDirection.Up);r.Item2.Value.StickNormalized=1;Step(r,120);A(r.Item1.State==AssistState.MANUAL_OVERRIDE&&r.Item3.LastCommand==0,"manual override immediate");Step(r,120);A(r.Item1.State==AssistState.MANUAL_OVERRIDE,"requires neutral");r.Item2.Value.StickNormalized=.5;Step(r,120);A(r.Item1.State==AssistState.IDLE,"neutral returns idle");}
 static void IntegrationTests(){var r=Rig();r.Item1.Start(GestureDirection.Up);double commandFar=0;for(var alt=100d;alt<=501;alt+=5){Step(r,alt);if(alt==105)commandFar=r.Item1.DesiredCommand;if(r.Item1.State==AssistState.HOLD)break;}A(commandFar>0&&r.Item3.LastCommand==0&&r.Item1.State==AssistState.HOLD,"model climb settles/release");r=Rig(500);r.Item1.Start(GestureDirection.Down);for(var alt=500d;alt>=49;alt-=5){Step(r,alt);if(r.Item1.State==AssistState.HOLD)break;}A(r.Item1.State==AssistState.HOLD&&r.Item3.LastCommand==0,"model descent settles/release");r=Rig();r.Item1.Start(GestureDirection.Up);r.Item2.Value.Connected=false;Step(r,150);A(r.Item1.State==AssistState.FAILSAFE&&r.Item3.LastCommand==0,"disconnect failsafe");}
}
